parser: '@typescript-eslint/parser'
env:
  browser: true
  node: true
  es6: true
parserOptions:
  ecmaVersion: 2020
  sourceType: "module"
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: "detect"
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
plugins:
  - '@typescript-eslint'
  - 'prettier'
  - 'react'
  - 'react-hooks'
rules:
  "react/no-children-prop": "off"
  "react/react-in-jsx-scope": "off"
  "@typescript-eslint/ban-ts-comment": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"