name: Pull Request
on: [pull_request]
env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PORT: 8080
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn install
    - name: Lint
      run: yarn lint
  test:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start