name: Test
on: [push]
env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PORT: 8080
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Component and E2E test
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
      - name: API Unit test
        run: yarn test:api
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}